language: php

php:
   - 5.3
   - 5.4

before_script:
   - wget http://getcomposer.org/composer.phar
   - php composer.phar config preferred-install source
   - ant -Dsystem.composer=composer.phar -Dcomposer.dev=--dev init

script:
   - ant -f build-dev.xml -Dmysql.root.user=root -Dmysql.root.password="" -Dmoodle.create-database=1 moodle-automation-init CI-build
