language: php

php:
   - 5.3

before_script:
   - wget http://getcomposer.org/composer.phar
   - ant -Dsystem.composer=composer.phar init

script:
   - phpunit --coverage-text 

notifications:
   email:
      - covex.mobile@gmail.com
